title: Michitaka Yoshida
logo: /assets/img/s-IMG_8038-2.jpg
description: Michitaka Yoshida is a Ph.D. student in Osaka University.
show_downloads: false
google_analytics: UA-160382453-1
theme: jekyll-theme-minimal
