title: Michitaka Yoshida
logo: /assets/img/s-IMG_8038-2.jpg
description: Michitaka Yoshida is a Ph.D student in Osaka University.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
